apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-helm-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/ykapilesh/my-flask-helm-app.git'
    targetRevision: HEAD
    path: charts/flask-app
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
